version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Helsinki"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react-native"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "react-test-renderer"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
