source "https://rubygems.org"

gem "fastlane", "2.235.0"
gem "multi_json"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
