export const knownWarningTypes = [
  'Aerodrome Warning For Tsunami',
  'Aerodrome Warning For Visibility',
  'Aerodrome Warning For Wind',
  'Bush Fire Advisory',
  'Bush Fire Watch',
  'Bush Fire Warning',
  'Drought Alert',
  'Drought Warning',
  'Falling Temperatures Advisory',
  'Flash Flood Advisory Discontinuation',
  'Flash Flood Advisory',
  'Flash Flood Watch Discontinuation',
  'Flash Flood Watch',
  'Flash Flood Warning Discontinuation',
  'Flash Flood Warning',
  'Flood Advisory',
  'Flood Watch',
  'Flood Warning',
  'Heat Advisory',
  'Heat Watch',
  'Heat Warning',
  'Heavy Rain at Sea Advisory',
  'Heavy Rain at Sea Warning',
  'Heavy Rainfall Advisory',
  'Heavy Rainfall Watch',
  'Heavy Rainfall Warning',
  'High Humidity Advisory',
  'High Humidity Warning',
  'High Surf Advisory',
  'High Surf Warning',
  'Hurricane Advisory Discontinuation',
  'Hurricane Advisory',
  'Hurricane Watch Discontinuation',
  'Hurricane Watch',
  'Hurricane Warning Discontinuation',
  'Hurricane Warning',
  'Landslide Advisory',
  'Landslide Watch',
  'Landslide Warning',
  'Large Wave Warning for Small Craft',
  'Poor Visibility',
  'Rainfall Outlook Drought',
  'Rainfall Outlook Heavy Rain',
  'Severe Weather Alert',
  'Storm Surge Advisory',
  'Storm Surge Warning',
  'Strong Wind and Large Waves Advisory',
  'Strong Wind and Large Wave Warning',
  'Strong Wind Advisory',
  'Strong Wind Watch',
  'Strong Wind Warning',
  'Temperature Outlook',
  'Thunderstorm Advisory',
  'Thunderstorm Watch',
  'Thunderstorm Warning',
  'Thunderstorm at Sea Warning',
  'Tropical Storm Advisory Discontinuation',
  'Tropical Storm Advisory',
  'Tropical Storm Watch Discontinuation',
  'Tropical Storm Watch',
  'Tropical Storm Warning Discontinuation',
  'Tropical Storm Warning',
  'Tsunami Alert Discontinuation',
  'Tsunami Alert',
  'Tsunami Watch Discontinuation',
  'Tsunami Watch',
  'Tsunami Warning Discontinuation',
  'Tsunami Warning',
  'Very Poor Visibility',
] as const;

export const severityList = ['', 'Moderate', 'Severe', 'Extreme'] as const;
