export const knownWarningTypes = [
  'Aerodrome Warning For Visibility',
  'Aerodrome Warning For Wind',
  'Bush Fire Advisory',
  'Bush Fire Warning',
  'Bush Fire Watch',
  'Drought Alert',
  'Drought Warning',
  'Falling Temperatures Advisory',
  'Flash Flood Advisory',
  'Flash Flood Warning',
  'Flash Flood Watch',
  'Flooding Advisory',
  'Flooding Warning',
  'Flooding Watch',
  'Heat Advisory',
  'Heat Warning',
  'Heat Watch',
  'High Humidity Advisory',
  'High Humidity Warning',
  'High Surf Advisory',
  'High Surf Warning',
  'Hurricane Advisory',
  'Hurricane Warning',
  'Hurricane Watch',
  'Landslide Advisory',
  'Landslide Warning',
  'Landslide Watch',
  'Large Wave Warning for Small Craft 2',
  'Large Wave Warning for Small Craft',
  'Poor Visibility',
  'Rainfall Outlook',
  'Severe Weather Alert',
  'Strong Wind Advisory',
  'Strong Wind and Large Wave Warning',
  'Strong Wind and Large Waves Advisory',
  'Strong Wind Warning',
  'Strong Wind Watch',
  'Tropical Storm Advisory',
  'Tropical Storm Warning',
  'Tropical Storm Watch',
] as const;

export const severityList = ['', 'Moderate', 'Severe', 'Extreme'] as const;
