export const knownWarningTypes = [
  'Aerodrome Warning For Visibility',
  'Aerodrome Warning For Wind',
  'Bush Fire Advisory',
  'Bush Fire Watch',
  'Bush Fire Warning',
  'Drought Alert',
  'Drought Warning',
  'Falling Temperatures Advisory',
  'Flash Flood Advisory',
  'Flash Flood Watch',
  'Flash Flood Warning',
  'Flooding Advisory',
  'Flooding Watch',
  'Flooding Warning',
  'Heat Advisory',
  'Heat Watch',
  'Heat Warning',
  'Heavy Rain at Sea Advisory',
  'Heavy Rain at Sea Warning',
  'Heavy Rainfall Advisory',
  'Heavy Rainfall Watch',
  'Heavy Rainfall Warning',
  'High Humidity Advisory',
  'High Humidity Warning',
  'High Surf Advisory',
  'High Surf Warning',
  'Hurricane Advisory',
  'Hurricane Watch',
  'Hurricane Warning',
  'Landslide Advisory',
  'Landslide Watch',
  'Landslide Warning',
  'Large Wave Warning for Small Craft',
  'Poor Visibility',
  'Rainfall Outlook',
  'Severe Weather Alert',
  'Strong Wind Advisory',
  'Strong Wind and Large Waves Advisory',
  'Strong Wind and Large Wave Warning',
  'Strong Wind Watch',
  'Strong Wind Warning',
  'Thunderstorm Advisory',
  'Thunderstorm Watch',
  'Thunderstorm Warning',
  'Thunderstorm at Sea Warning',
  'Tropical Storm Advisory',
  'Tropical Storm Watch',
  'Tropical Storm Warning',
] as const;

export const severityList = ['', 'Moderate', 'Severe', 'Extreme'] as const;
