# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #  gradle(task: "test")
  # end
  
  # Set Slack webhook
  slack_url = ENV["SLACK_WEB_HOOK_URL"]
  
  # Sign, build and deploy to Google Play Store
  desc "Sign, build, and deploy to Google Play Store"
     lane :build_sign_and_deploy do
	get_version_code_and_version_name
	build_and_sign
	deploy
   end
  
  # Get version code and version name.
  # Version code have to be greater than
  # Google Play store version code.
  desc "Get version code and version name"
     lane :get_version_code_and_version_name do
	# ensure_git_status_clean
	android_get_version_code(app_project_dir: './android/app/')
	android_get_version_name(app_project_dir: './android/app/')
  end

  # Validate Google Play Store key, build and sign aab
  desc "Release for the Android beta"
    lane :build_and_sign do
	# Validate Google Play Store key
	validate_play_store_json_key(
  		json_key: ENV["ANDROID_JSON_KEY_FILE"]
	)
	# Gradle clean
        gradle(task: 'clean', project_dir: './android')
	# Gradle sign aab -file
	gradle(task: 'bundle', build_type: "Release", project_dir: './android',properties: {
            "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_FILE"],
            "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_ALIAS"],
            "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
        })
   end
  
  # Deploy to Google Play Store
  desc "Deploy a new version to the Google Play"
    lane :deploy do
	  # Supply via Fastlane supply -command to Google Play Store
	  supply(package_name: 'jm.gov.metservice', json_key: ENV["GPLAY_JSON_KEY_FILE"], track: 'internal', release_status: 'draft')
  end
	
  # Build uploading success message to Slack, if lanes are completed successfully
  after_all do |lane|
    	slack(
              message: "Android Aab built and uploaded successfully to Google Play Store !",
              success: true,
              slack_url: slack_url
	)
   end
	
   # Error message to Slack
   error do |lane, exception|
    	slack(
      	      message: exception.message,
              success: false,
              slack_url: slack_url
	)
    end
end
